package com.gamemaster.gmapp.service;

import com.gamemaster.gmapp.GameSession;
import com.gamemaster.gmapp.Player;
import com.gamemaster.gmapp.dto.CreatePlayerRequest;
import com.gamemaster.gmapp.repository.PlayerRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Service layer for handling business logic related to Player entities. This will interact with the PlayerRepository
 * to perform CRUD operations and any additional business rules that may be needed in the future.
 */
@Service
public class PlayerService {

    private PlayerRepository playerRepository; // Repository for accessing player data from the database
    private GameSessionService gameSessionService; //Including this because it's needed to get the GameSession reference for creating a new Player, since session_id is not nullable.


    public PlayerService(PlayerRepository playerRepository, GameSessionService gameSessionService) { this.playerRepository = playerRepository; this.gameSessionService = gameSessionService; } // Constructor injection for the repository

    // Method to retrieve all players from the database
    public List<Player> getAllPlayers() {
        return playerRepository.findAll();
    }

    // Method to retrieve a specific player by their unique ID
    public Optional<Player> findById(UUID id) {
        return playerRepository.findById(id);
    }

    // Method to create a new player and save it to the database
    public Player createPlayer(CreatePlayerRequest createPlayerRequest) {

        /* First, we need to retrieve the GameSession entity that the new Player will be associated with, using the sessionId
         * from the CreatePlayerRequest DTO. If the GameSession is not found, we throw an exception which prevents the creation
         * of a Player without a valid GameSession reference, which would violate the non-nullable constraint on the session_id field in the Player entity. */
        GameSession gameSession = gameSessionService.findById(createPlayerRequest.getSessionId()).orElseThrow(()-> new RuntimeException("Game session not found for id: " + createPlayerRequest.getSessionId()));

        Player player = new Player();
        player.setGameSession(gameSession);
        player.setDisplayName(createPlayerRequest.getDisplayName());
        player.setColorHex(createPlayerRequest.getColorHex());
        player.setTurnOrder(createPlayerRequest.getTurnOrder());
        //Id and isGameMaster are not set here because id will be generated by the database and isGameMaster is a boolean that defaults to false, so it will be false unless explicitly set to true in the CreatePlayerRequest.

        return playerRepository.save(player);
    }
}
